<?php

namespace Templates;

use League\Plates\Template\Template;
use League\Plates\Template\TemplateClassInterface;

class Layout implements TemplateClassInterface
{

    /**
     * @param string[] $test323
     */
<<<<<<< HEAD
    public function display(Template $tpl, string $company = null, ?string $title = null ): void { ?>
=======
    public function display(Template $tpl, string $company, ?string $title = null ): void { ?>
>>>>>>> template-class
<html>
<head>
    <title><?=$tpl->e($title)?> | <?=$tpl->e($company)?></title>
</head>
<body>

<?=$tpl->section('content')?>

<?=$tpl->section('scripts')?>

</body>
</html>
<?php
    }
    /**
<<<<<<< HEAD
     * Autogenerated constructor
    */
    public function __construct(public string $company = null, public ?string $title = null)
=======
     * Autogenerated constructor.
     */
    public function __construct(public string $company, public ?string $title = null)
>>>>>>> template-class
    {
    }
}